Criando o script para adicionar amigo
devs-e-perigosos/amigo-secreto pull request #15
Opened 2022-03-19 04:42 UTC by JoaoAlfredoAlves

Criando o script para adicionar amigo ao BD já com funcionalidade de erro, caso o amigo já esteja adicionado e mensagem de cadastrado com sucesso, caso o amigo ainda não tenha sido adicionado.

2022-03-19 12:25 UTC, lyzzandro approved these changes

2022-03-20 05:35 UTC, alyssonaldrin approved these changes

2022-03-20 05:36 UTC, alyssonaldrin requested changes

2022-03-20 05:36 UTC, alyssonaldrin commented on frontend/scripts/tela-cadastro.js
> +    else botaoOk.className += " botao-ok";
adiciona a logica do botao redirecionar e os estilos na mensagem de erro e depois so dale

2022-03-20 12:11 UTC, lyzzandro approved these changes

2022-03-20 19:35 UTC, JoaoAlfredoAlves commented on frontend/scripts/tela-cadastro.js
> +    else botaoOk.className += " botao-ok";
sim sim, vou fazer isso, ai é só começando a criação do script

2022-03-21 19:17 UTC, alyssonaldrin approved these changes

2022-03-21 19:18 UTC, merged