Criando Página de Cadastramento
devs-e-perigosos/amigo-secreto pull request #7
Opened 2022-03-08 22:51 UTC by JoaoAlfredoAlves

Criando a página HTML de Cadastramento e seu respectivo CSS

2022-03-08 23:12 UTC, lyzzandro approved these changes

2022-03-09 00:51 UTC, alyssonaldrin requested changes

2022-03-09 00:51 UTC, alyssonaldrin commented on frontend/pages/tela-cadastro.html
> +        <h2 id="h2-nome">Nome</h2>
a tag h2 aki não está semanticamente correta, ideal seria usar a tag label

2022-03-09 00:51 UTC, alyssonaldrin commented on frontend/pages/tela-cadastro.html
> +        <h2 id="h2-email">E-mail</h2>
a tag h2 aki não está semanticamente correta, ideal seria usar a tag label

2022-03-09 00:51 UTC, alyssonaldrin commented on frontend/pages/tela-cadastro.html
> +        <input
usar tag button leitor de tela ficaria confuso

2022-03-09 00:51 UTC, alyssonaldrin commented on frontend/styles/tela-cadastro.css
> +}
usar classe ao invés de id, e seria bom concentrar as propriedades apenas nela, assim fica mais fácil de ler o código

2022-03-09 00:51 UTC, alyssonaldrin commented on frontend/pages/tela-cadastro.html
> +        <input
usar tag button leitor de tela ficaria confuso

2022-03-09 01:13 UTC, alyssonaldrin approved these changes

2022-03-09 01:13 UTC, merged